doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
#                metadata_cache_driver: apc
#                result_cache_driver: apc
#                query_cache_driver: apc
                query_cache_driver: array
                result_cache_driver: array
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    TargetBundle: ~

    dbal:
        default_connection: "default"
        connections:
            default:
                driver:   "pdo_mysql"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                server_version: 5.6
                charset:  UTF8
                options:
#                    #Разрешаем загруку данных из файлов  LOAD DATA LOCAL INFILE
#                    1001: true
                mapping_types:
                    enum: string